# Generated by Django 4.1.7 on 2023-03-07 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id_detalle',
            field=models.UUIDField(default=uuid.UUID('42c294b3-1397-4fee-b145-a40deb6f1420'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.UUIDField(default=uuid.UUID('361dbb59-bdd8-4980-b8ce-7e30dfb75c6e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('dd25dd58-25a4-403a-8d20-855843e63135'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.UUIDField(default=uuid.UUID('1999507e-469c-4c1c-b325-73c6e825ac1a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
